name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'  # 每天运行一次
  workflow_dispatch:     # 手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Fork Repository
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Add Upstream
      run: |
        git remote add upstream https://github.com/GuooGaii/ip-geoaddress-generator
        git fetch upstream
        git merge upstream/main --no-edit
        git push origin main
